- backend/index.js
- frontend/src/pages/Signup/Signup.jsx
- frontend/src/utils/helper.js
Description:
This pull request introduces form field validations for the following fields in both the frontend and backend:
- Email: Ensures valid email format.
- Password: Enforces minimum length and strong password requirements.
- Name: Checks for non-empty and invalid format inputs .
Changes Made:
Frontend:
- Added validation logic to the signup forms.
- Displayed error messages for any field related errors.
Backend:
- Implemented validation checks in the API endpoints for creating account / signup .
- Proper error handling in case of failed validations.
> Add Form Field Validations for Email, Password, and Name during SignUp

- backend/.env.development
- backend/.env.production
- backend/.gitignore
- frontend/.env.development
- frontend/.env.production
- frontend/.gitignore
This pull request adds a ```.gitignore``` file to the project's ```frontend``` and ```backend``` folder to prevent sensitive files, such as ```.env``` files, and other unnecessary files from being tracked and committed to the repository.
Issue ```#28```
> Add .gitignore to Exclude Sensitive and Unnecessary Files

- backend/index.js
- backend/utils/const.js
This PR introduces the following updates:
Created a const.js file to centralize all dynamic messages used across the project.
Moved all hardcoded strings to const.js to improve maintainability and consistency.
Exported the dynamic messages from const.js and imported them into relevant files.
Replaced hardcoded messages with references to the dynamic constants, making the code easier to update and localize in the future.
Why this change was made:
Improved maintainability: Centralizing messages allows for easier updates and ensures consistent messaging throughout the codebase.
Scalability: This structure facilitates future changes (e.g., localization or message customization) without altering multiple files.
Code cleanliness: The change reduces repetition and hardcoding, leading to cleaner …
> #20 Dynamic Messages

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Feat : #29 
I've created .github directory in the project root and added PULL_REQUEST_TEMPLATE.md and ISSUE_TEMPLATE.md file.
> Add PR and ISSUE Template

- frontend/src/components/Input/TagInput.jsx
This PR fixes the issue where only the icon within the button had the event listener. Now, the entire button is clickable, enhancing the user experience.
> Fix event listener on button for full clickable area

- backend/index.js
- frontend/src/pages/ProfilePage/ProfilePage.jsx
**Description:** This pull request implements a new API endpoint to facilitate the deletion of a user along with all their associated notes. 
**Changes Made:**
New API Endpoint:
**Endpoint:** DELETE /delete-user
**Functionality:**
Deletes all notes associated with the specified user ID.
Deletes the user from the database.
Returns a confirmation message.
**Authorization Checks:**
Ensures that only the authenticated user can delete their own account .
**Error Handling:**
Properly handles scenarios where the user does not exist, returning appropriate HTTP status codes and messages.
**On successful deletion:**
- The user is redirected to the signup page.
- A success notification is displayed to inform the user of the successful deletion. …
> Add API for Deleting User and Associated Notes

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Have made the necessary changes to the documentation by adding a CONTRIBUTING.md and CODE_OF_CONDUCT.md file
- Fixes #58
> Documentation improvement - Added 

- frontend/src/App.jsx
- frontend/src/components/Footer.jsx
- frontend/src/components/sticky_footer/Content.jsx
- frontend/src/components/sticky_footer/Footer.jsx
- frontend/src/main.jsx
- frontend/src/pages/Signup/Signup.jsx
- frontend/src/utils/axiosInstance.js
- Fixes #45 
- [done ] My code follows the style guidelines of this project
- [ done] I have performed a self-review of my own code
- [ done] I have commented my code, particularly in hard-to-understand areas
- [ done] My changes generate no new warnings
- [ done] New and existing unit tests pass locally with my changes
- [ done ] I have maintained a clean commit history by using the necessary Git commands
- [ done] I have checked that my code does not cause any merge conflicts
https://github.com/user-attachments/assets/a5ed1515-997c-4aea-be0f-d55a8aead3b9
> feat:#45 modern footer added

- backend/index.js
- frontend/src/components/Footer.jsx
This PR addresses issue#49 by fixing error during signup and login .
Screen Recording of Visual Changes
[Screencast from 2024-10-03 22-59-20.webm](https://github.com/user-attachments/assets/fd6e95e8-8dfb-481f-b207-6b15783879cd)
updated envPath according to development
How to Test
- Go to Website
- Fill user details
- click on create an account button and see the changes
Related Issues
Fixes #49
> fix signup and login error issue #49

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Footer.jsx
- frontend/src/components/sticky_footer/Content.jsx
Added a button at the bottom right of the button. When clicked it'll scroll to the top of the page. As asked, it only appears on the landing page and NOT on any other page of the website.
- Fixes #59 
- New feature (non-breaking change which adds functionality)
> Added the scroll to top button #59

- backend/index.js
- frontend/src/components/Footer.jsx
- frontend/src/pages/ProfilePage/ProfilePage.jsx
This PR addresses issue#50 by fixing phone number validation in Profile and Setting Section.
[Screencast from 2024-10-03 20-05-28.webm](https://github.com/user-attachments/assets/b73e29f7-138a-431c-89dd-ff6c6798e9b9)
Added a phone number validation function.
Go to Profile and Setting section
Click on Change Phone Button
Enter anything in input field , if it is a valid number ,it updates otherwise shows a error toast
Fixes https://github.com/Scribbie-Notes/notes-app/issues/50
> fix phone number validation issue #50

- backend/config.json
There was a config.json file in the backend folder that was unnecessarily revoking the security of the code base by adding the MongoDB Atlas connection String to GitHub.
I removed the track of git of the file from the folder and deleted the file.
- Fixes #38 
> Fix accidental upload of MongoDB URI through config.json file from backend

- backend/index.js
- Fixes #37 
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- New and existing unit tests pass locally with my changes
- I have maintained a clean commit history by using the necessary Git commands
- I have checked that my code does not cause any merge conflicts.
> Bug Fixes and Feature Enhancements: User Registration, Login, and Profile Updates

- backend/index.js
- backend/utils/const.js
- frontend/src/pages/ProfilePage/ProfilePage.jsx
Description
Fixes #26 
[ done] Bug fix (non-breaking change which fixes an issue)
[ done] New feature (non-breaking change which adds functionality)
Checklist
[done ] My code follows the style guidelines of this project
[done ] I have performed a self-review of my own code
[done ] I have commented my code, particularly in hard-to-understand areas
[ done] My changes generate no new warnings
[ done] New and existing unit tests pass locally with my changes
[ done] I have maintained a clean commit history by using the necessary Git commands
[done ]I have checked that my code does not cause any merge conflicts
> name change feature added

- README.md
I have added all the contributors in readme.md file to give them appreciation.
- Fixes #109 
> Additon of All Contributors | Issue #109

- frontend/src/components/Cards/ProfileInfo.jsx
I added a modal which confirms logout of the user 
- Fixes #107 
> added modal for logout confirmation

- backend/index.js
- backend/models/noteModel.js
- frontend/src/components/Input/AddAttachmentInput.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- Fixes #15 
- [done] Added an attachments field to store the paths of uploaded files while making notes.
- [done] The frontend has been updated to allow file uploads.
- [done] Add an attachment field to upload files directly to the upload folder, and send the file path to the backend to store the uploaded file's path.
- [pending] Edit the attachment.
- [pending] Delete the uploaded attachment data from the upload folder and remove its path from the database.
- [done ] My code follows the style guidelines of this project
- [ done] I have performed a self-review of my own code
- [done ] I have commented my code, particularly in …
> Note Schema updated

- frontend/src/pages/ProfilePage/ProfilePage.jsx
added a email validator to the Profile Page #46 
- Fixes #46
> email validation added in profile page

- frontend/src/components/Testimonial.jsx
Update the testominal page with good animations
- Fixes #11
- [x}I have checked that my code does not cause any merge conflicts
> modified the testominal page with slick animations

- frontend/src/App.jsx
- frontend/src/components/Hero/Hero.jsx
- frontend/src/components/Navbar.jsx
- package-lock.json
- package.json
- Fixes #10 
- [] Bug fix (non-breaking change which fixes an issue)
https://github.com/user-attachments/assets/823352a4-52bd-4c3a-92e6-421ae0635a82
> added gsap to animate the website

- frontend/src/index.css
Scroll bar added
- Fixes #140 
- [ 1] New feature (non-breaking change which adds functionality)
- [ 1] My code follows the style guidelines of this project
- [ 1] I have performed a self-review of my own code
- [1 ] I have commented my code, particularly in hard-to-understand areas
- [1 ] My changes generate no new warnings
- [1 ] New and existing unit tests pass locally with my changes
- [1 ] I have maintained a clean commit history by using the necessary Git commands
- [ 1] I have checked that my code does not cause any merge conflicts
https://github.com/user-attachments/assets/28f7078b-0806-4402-8d6c-915173bd6319
i have added color which i like you can change color according to you in index.css file or you can just tell me which color …
> scroll bar added : Added scroll bar on your website #140 done

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Pricing.jsx
- Fixes #12 
https://github.com/user-attachments/assets/0f2e51a3-a288-4afb-8ebc-25e10142c90b
> redesign  pricing page

- backend/utils/const.js
This PR fix #141 
This PR fix 2 issues - 
[x] Login endpoint is returning 400 error without any error message
[x] After login / signup all other api call is failing with status code 403
- Fixes
#141 
https://github.com/user-attachments/assets/f61d79b7-8abe-4c5f-a69f-aa541e2a6ddd
> Fix login 400 error + After login/signup all api calls fail with 403 error

- backend/Routes/Router.js
Fix: getting Token verification is failed in api calls
- Fixes #149
> fix: all api's getting fail with 403 error after login/signup

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/components/Tabs.jsx
> added navbar

- frontend/src/assets/images/cross.svg
- frontend/src/components/Faq.jsx
- frontend/src/components/Hero/Hero.jsx
This pull request implements a dedicated FAQ page at the bottom of the page, aimed at enhancing user engagement and support. The page provides clear, concise answers to commonly asked questions, thereby streamlining the user experience.
- Fixes #157 
This change introduces a new feature (in this case, the FAQ page).
https://github.com/user-attachments/assets/5b464383-54ae-400b-a81b-a27af0fc6023
> [Feat]: FAQ page added successfully

- backend/Routes/Router.js
- frontend/src/components/Cards/NoteCard.jsx
- frontend/src/pages/Home/Home.jsx
This PR implements a feature that allows users to update the background color of multiple notes at once. Instead of making individual API calls for each selected note, the update is done in a single request, improving performance and enhancing user experience.
- Fixes #167
-feature added
[Screencast from 2024-10-12 12-24-56.webm](https://github.com/user-attachments/assets/109bed02-5691-4e17-9300-9fcdc42a69ce)
> adding background color functionality of multiple notes together

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Cards/NoteCard.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- frontend/src/pages/Home/Home.jsx
Add text formatting options: bold, italic, underline, headings, and lists in note editor
- Fixes (#160)
- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [yes ] My changes generate no new warnings
- [ yes] New and existing unit tests pass locally with my changes
- [yes ] I have maintained a clean commit history by using the necessary Git commands
- [yes ] I have checked that my code does not cause any merge conflicts
> Implement basic text formatting options in note editor

- frontend/src/App.jsx
- frontend/src/components/Contact/Contact.jsx
- frontend/src/components/Pricing.jsx
- frontend/src/components/Testimonial.jsx
- Resolved an issue where the header component was not rendering on certain routes.
- Updated route configuration to ensure the header is consistently displayed across all relevant pages.
- Verified that the header now renders correctly when navigating between different routes.
- Fixes #170
-bug fix
[Screencast from 2024-10-13 07-35-32.webm](https://github.com/user-attachments/assets/ab872c8f-b2f6-4868-98e9-d7b8a614628b)
> Fix Header Not Displaying on Various Routes

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components/Contributors/Contributors.css
- frontend/src/components/Contributors/Contributors.jsx
- frontend/src/components/Footer.jsx
Added Contributor's Page that matches the theme of website.
- Fixes #172
https://github.com/user-attachments/assets/9cbea88a-1cad-4057-b2aa-8ac6f234edea
> Added Contributor's Page

- backend/Routes/Router.js
- frontend/src/components/Cards/NoteCard.jsx
- frontend/src/pages/Home/Home.jsx
This PR introduces the functionality to pin and unpin multiple notes at once. Users can now select multiple notes and perform the following actions:
**Pin multiple notes:** Selected notes will be pinned and displayed at the top of the list.
**Unpin multiple notes:** Pinned notes can be unpinned and will return to their original positions in the notes list.
- Fixes #183
-feature addded
[Screencast from 2024-10-15 11-59-38.webm](https://github.com/user-attachments/assets/973c7870-0c26-4dd0-9078-69b4a4a967cf)
> Implement Pinning and Unpinning Multiple Notes

- backend/Routes/Router.js
- backend/models/noteModel.js
- frontend/src/App.jsx
- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
- frontend/src/components/Cards/ProfileInfo.jsx
- frontend/src/pages/Home/Home.jsx
This PR introduces a new feature that allows users to archive their notes. Archived notes will be stored separately from active notes, and users will be able to view them in a dedicated section. The main changes include:
- Backend API updates to support archiving/unarchiving notes.
- Frontend updates to display archived notes in a new view.
- Adjustments to the note schema to include the isArchived field.
- Fixes #194 
[Screencast from 2024-10-16 19-21-40.webm](https://github.com/user-attachments/assets/7dce6303-e165-48e2-8fff-a3435ff7bf83)
> Add Feature to Archive Notes

- frontend/src/components/Contact/Contact.jsx
this PR introduces a new "Contact Us" page to the application. The page includes a form that allows users to submit inquiries and contact information.The form includes fields for first name, last name, email, and a message, along with a checkbox for subscribing to company updates.
- Fixes #181
> added contact us page

- frontend/src/components/Hero/Hero.jsx
- frontend/src/components/Pricing.jsx
- frontend/src/components/Testimonial.jsx
**Before**
**After**
https://github.com/user-attachments/assets/2ecc6088-8833-495a-bb72-31f351d3718d
issue no #188
> Made animations visible every time it get's into the view, and removed repetition of navbar component among the home page.

- frontend/src/components/Footer.jsx
- frontend/src/components/GoogleTranslate.jsx
I have added Multi-Language Support Using Language Translator API that will helps to convert the website text to the multiple country languages.
- Fixes #202
https://github.com/user-attachments/assets/559a84a7-b7f6-40c2-a8a4-76e600b177cc
> Multi-Language Support Using Language Translator

- .gitignore
- frontend/.env.development
- frontend/src/App.jsx
- frontend/src/components/Preloader.jsx
Preloader added
- Fixes #95 
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
> preloader added

- frontend/src/components/Navbar.jsx
Fixed  #198 
- signup button next to login in Navbar
- Implemented GSAP animations for signup button
- Hide login/signup buttons on /signin
submitted for Hacktoberfest 2024
[Screencast from 2024-10-17 17-58-19.webm](https://github.com/user-attachments/assets/6edbaab4-0f6c-4f7a-bdf1-f6abe13f8a2a)
> #198 Signup added on Navbar

- frontend/src/components/Navbar.jsx
- frontend/src/pages/Home/Home.jsx
- Fixes #(220)
- The navbar lacked in the styling of the Login and Signup  button .
- This PR will solve that issue and I have made sure that I am following the scheme of the website . I have added basic style for the two button and a hover effect also .
**The Singup button shows the normal style and the Login button shows the style after hovering over it**
>  ISSUE #220 --fixed the UI of the button in navbar

- frontend/src/components/Tabs.jsx
This PR introduces distinct styling for active route links, making it easier for users to identify which page they are currently on. By changing the active link color, the navigation experience is more intuitive and user-friendly.
- Fixes #206 
-feature added
[Screencast from 2024-10-19 10-37-18.webm](https://github.com/user-attachments/assets/e0ae10af-8de9-42cb-a43f-aa320bd27e29)
> Make Active Route Link Color Distinct for Improved Navigation

- frontend/src/components/About/About.jsx
- Fixes #(221)
- I have updated the Ui of the About us a bit . I was trying some things but it would have altered the theme of the website .
- I wanted to add Gsap to it but I think it looks better this way .
> improved the Ui of the About Us page

- frontend/src/components/About/About.jsx
- frontend/src/components/Contact/Contact.jsx
- frontend/src/components/Footer.jsx
Fixed the bug of page rendering at bottom from footer and  also added the correct link for contact us in the footer section 
- Fixes #215 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] I have maintained a clean commit history by using the necessary Git commands
- [ x] I have checked that my code does not cause any merge conflicts
https://github.com/user-attachments/assets/28d49cea-03f1-46d9-bc90-496c1ca21849
> Fixed the bug

- frontend/package-lock.json
- frontend/src/App.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/components/Tabs.jsx
- frontend/src/components/Toggle.jsx
> add dark mode

- frontend/src/components/Cards/NoteCard.jsx
- frontend/src/components/FilterTags.jsx
- frontend/src/components/Input/TagInput.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- frontend/src/pages/Home/Home.jsx
Requested to add a filter toggle for tags in notes. This feature will allow users to filter notes by matching tag filters.
- feature #232 
- Go to the notes page.
- Enable the filter toggle.
- Select the desired tags to filter the notes.
```
frontend/src/components/Cards/NoteCard.jsx
frontend/src/components/FilterTags.jsx (new file)
frontend/src/components/Input/TagInput.jsx
frontend/src/pages/Home/AddEditNotes.jsx
frontend/src/pages/Home/Home.jsx
```
https://github.com/user-attachments/assets/099fe065-bdc2-41b2-87cc-b08e57115a8f
> Add filter options above to i can toggle via tags #232

- frontend/src/components/Footer.jsx
1. Resolved the issue where clicking the "Feedback" button in the footer was not displaying the modal as expected.
2. Now, clicking the "Feedback" button correctly opens the feedback modal, allowing users to submit their feedback.
3. Updated routing/handling to ensure smooth user experience when accessing the feedback form from the footer section.
- Fixes #128 
-bug fix
[Screencast from 2024-10-21 16-25-56.webm](https://github.com/user-attachments/assets/4ffcb2ee-a9c1-45f5-83dc-15c406e2eb97)
>  Fix Feedback Button to Display Modal in Footer

- backend/Routes/Router.js
- frontend/src/pages/Home/AddEditNotes.jsx
Fix mongodb query to update note
- Fixes #224 
> Fix mongodb query to update note

- frontend/src/components/Navbar.jsx
- frontend/src/pages/Home/Home.jsx
- frontend/src/setupProxy.js
- frontend/src/utils/axiosInstance.js
- frontend/src/utils/constants.js
This PR addresses an issue where the Login and Signup buttons were still visible on the UI when the user was already authenticated.
- Fixes #239
-bug fix 
[Screencast from 2024-10-21 21-48-20.webm](https://github.com/user-attachments/assets/ccb8fcd0-13af-45e9-b904-363bfe16d1e7)
> Fix: Hide Login and Signup Buttons When User is Logged In

- backend/Routes/Router.js
- backend/models/feedbackModel.js
- backend/models/noteModel.js
- frontend/src/components/About/About.jsx
- frontend/src/components/Footer.jsx
This PR fixes an issue where the feedback form was not submitting correctly. The following changes were made:
- Added proper validation checks to ensure all fields (name, email, feedback, and rating) are filled before submission.
- Handled the case where the loading spinner would not stop when validation fails.
- Enhanced error feedback to the user, ensuring that they are informed when required fields are missing.
- Improved the feedback submission flow to provide a better user experience by stopping the loading state when form validation fails.
- Fixes #237 
-bug fix
[Screencast from 2024-10-21 19-09-34.webm](https://github.com/user-attachments/assets/db16f50f-6f76-4e23-a99c-402ec0acc07c)
[Screencast from 2024-10-21 …
> Fix: Feedback form not submitting issue

- frontend/src/components/Input/AddAttachmentInput.jsx
- frontend/src/components/Input/TagInput.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- Made the height of Add note smaller to fit screen
- Also, adjusted margins for all elements.
- Fixes #225 
> Made height of add note smaller to fit screen

- backend/Routes/Router.js
- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
- frontend/src/pages/Home/Home.jsx
Added un-archive feature
- Fixes #226 
> Added un-archive feature

- backend/Routes/Router.js
- backend/mail/contactUsMailSender.js
- frontend/src/components/Contact/Contact.jsx
Adding contact us backend functionality using nodemailer.
- Fixes #257 
https://github.com/user-attachments/assets/38dc3960-6b46-409f-a912-03b7cf179c7e
@theashikagupta Please review my PR and merge it with labels:)
> Feat: Adding ContactUs Backend Functionality

- README.md
This pull request includes the following updates to the README file:
- Added relevant GitHub badges (stars, forks, issues, pull requests) for better project visibility and quick access to repository stats.
- Improved formatting for better readability and consistency.
- Updated content sections to clarify project goals, installation steps, and contribution guidelines.
- Enhanced the contribution section with detailed steps for new contributors.
https://github.com/user-attachments/assets/b7ff6db4-9acb-4f5f-9def-695e790db423
Please label this PR with:
- `gssoc-ext` for contributions under GirlScript Summer of Code Extended.
- `hacktoberfest-accepted` to ensure it counts towards Hacktoberfest.
> Updated README with additional details and badges

- frontend/src/pages/Home/AddEditNotes.jsx
TinyMCE is a rich-text editor that allows users to create formatted content within a user-friendly interface. I have integrated it in notes app.
Solves issue #176 
@theashikagupta @yashmandi 
kindly review my PR and provide the labels of gssoc extended,hactoberfest accepted and level 2.
Also let me know if there are any changes to be made.
> Integrated TinyMCE to notes app

- backend/Routes/Router.js
- backend/models/userModel.js
I have updated the Router.js and the user-model so that we can incorporate the hashing function at the document which forming for the user-Info . I have included two functions  1. to convert password 2. one to validate the password before logging in . 
I have debugged the code , added comments at necessary places and have verified the working of the code using both POSTMAN and the MONGODB . This PR will Fixes #265 
- Fixes #(265)
> updated the code base

- backend/Routes/Router.js
- backend/models/userModel.js
- frontend/src/pages/Login/Login.jsx
- frontend/src/pages/Signup/Signup.jsx
This PR addresses issue by fixing error during signup and login .
- Fixes #49 
-bug fix
**login recording**
[Screencast from 2024-10-25 22-07-26.webm](https://github.com/user-attachments/assets/e55d2842-8c61-4885-8ee2-eb2f6801b46c)
**signup recording **
[Screencast from 2024-10-25 22-06-12.webm](https://github.com/user-attachments/assets/5e753374-77b4-40ba-905b-944f751df224)
> Fix the error showing on signup and login

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/pages/Home/AddEditNotes.jsx
Description
This pull request introduces a new feature that adds microphone functionality to the note-taking app, allowing users to input notes via speech recognition. The microphone button starts and stops speech-to-text transcription, directly appending the user's speech to the note content. This enhancement improves accessibility and provides users with an alternative method of input.
Fixes # (issue number, if applicable)
Relevant Motivation and Context
The microphone functionality was added to make note-taking faster and more accessible, especially for users who prefer voice input or have difficulty typing. It uses the Web Speech API to convert speech to text. Additionally, error handling has been implemented to provide feedback when speech recognition is not supported or fails.
Type …
> Add mic succefully

- frontend/src/components/About/About.jsx
- frontend/src/components/Footer.jsx
- frontend/src/pages/ProfilePage/ProfilePage.jsx
- frontend/src/setupProxy.js
- frontend/src/utils/axiosInstance.js
> Remove hard-coding of URLs and use env variables

- backend/Routes/Router.js
- frontend/src/pages/Home/AddEditNotes.jsx
Added scrollbar and fixed margins for responsiveness for Add Note
- Fixes #275 
https://github.com/user-attachments/assets/1a00ed7f-3b57-407b-b49b-632db285336c
> Added scrollbar and fixed margins for responsiveness for Add Note

- frontend/src/components/Contact/Contact.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/components/Tabs.jsx
i made the navbar responsive and added a hamburger icon  
issue #286 
i also made the contact form responsive 
responsive contact form :
though it was a level1 issue but i also made the contact form responsive can you add level2 please  @theashikagupta
> Navbar responsive

- backend/Routes/Router.js
- backend/package-lock.json
- backend/package.json
i added a rate limiter to the login api now if too many invalid request come form a single api that api will be blocked for 5 minutes
advantage:
prevent any hacker attack
reduce the load on login api
- Fixes #284
login with correct credentials is successfull
login with invalid credentails is unsuccesfull
if i try to login many times with invalid credentials then the api will block the ip address for 5 minutes
please add gssoc-ext and level3 before merge @theashikagupta
> rate limiter to login api 

- frontend/src/utils/helper.js
> Apply validations in all forms

- frontend/src/pages/Home/AddEditNotes.jsx
- frontend/src/pages/Home/Home.jsx
- frontend/src/pages/Login/Login.jsx
- frontend/src/pages/ProfilePage/ProfilePage.jsx
- frontend/src/pages/Signup/Signup.jsx
i corrected the url in all the axios request you are making the http://localhost:5000 was missing from the url 
http://localhost:5000 this is the address where your backend is running
- Fixes #285 
please add gssoc-ext and level2 before  merge @theashikagupta
> added proper url

- .github/detect-duplicate-issues.yml
Create detect-duplicate-issues.yml
fixes #311
> Add GitHub Workflow for Auto-Closing Similar Issue Requests

- backend/index.js
Fix mongo env variable usage and backend server crash
- Fixes #309
> Fix mongo env variable usage and backend server crash

- frontend/src/components/Footer.jsx
Added app version page
- Fixes #315
> Added app version page

- backend/Routes/Router.js
- backend/models/contactModel.js
- frontend/src/components/Contact/Contact.jsx
- frontend/src/components/Navbar.jsx
Added new contact collection for saving Contact Us info
- Fixes #312
> Added new contact collection for saving Contact Us info

- backend/Routes/Router.js
- frontend/src/components/Navbar.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- Modified update note pinned mongodb query
- Fixed merge changes
- Fixes #310
> Fixed update note pinned mongodb query

- .github/auto-label.yml
This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests
- Fixes #313
> Implement Auto-Labeling Workflow for GitHub

- backend/Routes/noteRoutes.js
- backend/controllers/noteControllers.js
- backend/index.js
- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
I resolved issues with the un-archive-notes endpoint, ensuring successful bulk unarchiving of selected notes.
- Fixes #332 
-bug fix
[Screencast from 2024-10-29 14-28-15.webm](https://github.com/user-attachments/assets/21a2befd-a3cf-43ec-ad62-d013ae28ae1f)
> Fix: Unarchive Notes Functionality and Endpoint Response

- backend/Routes/eventRoutes.js
- backend/index.js
- backend/models/eventModel.js
- frontend/src/App.jsx
- frontend/src/components/Calendar/Calendar.jsx
- frontend/src/components/Tabs.jsx
"This PR introduces a new calendar component that allows users to add events on specific dates. Key features include:
**Calendar View**: Displays a monthly calendar view with navigation for switching between months.
**Event Addition**: Users can add events with details including date, title, color, and user ID.
**Event Display**: Events are displayed on their respective dates within the calendar, color-coded as specified by the user.
**Backend Integration**: Added Event schema in the database to store event data, with API routes for fetching and creating events.
- Fixes #345 
[Screencast from 2024-10-30 12-42-48.webm](https://github.com/user-attachments/assets/006c0b2a-457f-4bed-bf2d-2569a1155655)
> [feat] Add Calendar Functionality with Event Addition Capability

- backend/Routes/noteRoutes.js
- backend/controllers/noteControllers.js
- backend/middlewares/user.middlewares.js
- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
This PR introduces an undo feature for archived notes, allowing users to restore accidentally archived notes with a single action. Key updates include:
- Implemented undoDelete functionality that restores archived notes by updating their status.
- Fixes #344 
[Screencast from 2024-10-30 15-48-48.webm](https://github.com/user-attachments/assets/616340c4-0705-45fd-bcae-6a00e80016ff)
> Add Undo Functionality for Deletion of Archived Notes

- backend/Routes/Router.js
- backend/Routes/noteRoutes.js
- backend/controllers/noteControllers.js
- frontend/src/pages/Home/AddEditNotes.jsx
@yashmandi : Spend around 3 hours to fix this critical bug. I noticed that we have a duplication of router handlers. (Route.js and controllers/noteController) #354
- Fixed controller query which handles edit note
- Fixed token auth issue
- Added isPinned in request of edit note
- Fixed storing of tags in backend
Resolves #336 #327  
https://github.com/user-attachments/assets/6332da94-0f79-4fbf-8e38-ae8c0600ae35
> Fixed update note in frontend and backend

- frontend/src/components/Calendar/Calendar.jsx
- frontend/src/components/Modal.jsx
his PR introduces a feature to delete past or unimportant events, allowing users to manage their event list more effectively. This includes:
- Adding a delete option for each event.
- Implementing backend logic to remove events from the database.
- Updating the frontend to reflect event deletions immediately.
- Ensuring confirmation prompts to avoid accidental deletions.
- Fixes #349 
[Screencast from 2024-10-31 06-17-38.webm](https://github.com/user-attachments/assets/850e388a-a47d-4134-a8ee-661f0236e1ca)
> Add Functionality to Delete Past or Unimportant Events

- frontend/src/components/Calendar/Calendar.jsx
- frontend/src/components/Modal.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/components/Tabs.jsx
- frontend/src/pages/Home/Home.jsx
This PR adds an undo functionality for the deletion of primary notes, allowing users to recover notes immediately after deletion. Changes include:
- Implementing a temporary storage for deleted notes.
- Adding an 'Undo' option in the UI after note deletion.
- Setting a timeout for the undo option to expire after a few seconds.
- Fixes #350 
[Screencast from 2024-10-31 06-29-55.webm](https://github.com/user-attachments/assets/da265014-f26c-43fd-95ad-b3cd23b99b72)
> Add Undo Functionality for Deletion of Primary Notes

- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- Added Edit option for archive notes
- Fixes #328 
https://github.com/user-attachments/assets/3dfc2d66-b357-47a1-b575-dfc038cbbb27
> Feature: Add Edit option for archive notes

- backend/Routes/eventRoutes.js
- frontend/src/components/Calendar/Calendar.jsx
- Modified all event routes and added default color
- Added validation for creating event
- Fixes #357 
https://github.com/user-attachments/assets/b0bbd6f3-f8c8-4bb7-9deb-c29621a7ccb7
> Modified all event routes and added default color

- frontend/src/components/Calendar/Calendar.jsx
- Add tailwind class to wrap event title
- Fixes #358 
https://github.com/user-attachments/assets/bbd84c16-bbbe-41b5-a594-ca83edea7913
> Add tailwind class to wrap event title

- frontend/src/components/Navbar.jsx
- frontend/src/pages/Home/Home.jsx
This PR updates the navbar component to be fully responsive across various screen sizes. Key adjustments include layout and styling changes to ensure smooth transitions on mobile, tablet, and desktop views. The navbar now adapts to smaller screens with a collapsible menu for enhanced usability on mobile devices.
- Fixes #322 
-bug fix
[Screencast from 2024-10-31 23-32-09.webm](https://github.com/user-attachments/assets/5d179bba-c362-44dd-9036-a15646b79aad)
> Make Navbar Responsive

- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
- Added update Pin method for archive notes
- 
- Fixes #356 
https://github.com/user-attachments/assets/bb00a59e-d07d-45e2-8664-d758e6f6ce3a
> Added update Pin method for archive notes

- frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
- Added view modal for archive notes (works for pinned note as well)
- Fixes #372 
- Also, fixed delete note issue #227 , which was overwritten
https://github.com/user-attachments/assets/b49233e3-bd72-4b48-ad01-7b3192cf8bae
> Added view modal for archive notes (works for pinned note as well)

- frontend/src/components/Navbar.jsx
- Save theme in local storage and fetch it after refresh
- Fixes #370 
https://github.com/user-attachments/assets/99e109b6-7124-42ad-8301-5c59171e356f
> Save theme in local storage and fetch it after refresh

- frontend/src/components/Navbar.jsx
- frontend/src/pages/Home/Home.jsx
- Fixed home page card disable bug & removed hardcoding URLs
- Fixes #368 
https://github.com/user-attachments/assets/95ef886e-e6cb-47f9-b449-84045345c577
> Fixed home page card disable bug & removed hardcoding URLs

- backend/controllers/noteControllers.js
- frontend/src/hooks/noteActions.jsx
- frontend/src/pages/Home/AddEditNotes.jsx
- Added custom hook for Add, Edit notes
- Fixed edit note error when tags array is undefined
- Improved readability of code
- Fixes #377 
NA
> Added custom hook for Add, Edit notes

- backend/Routes/eventRoutes.js
- backend/models/eventModel.js
- frontend/src/components/Calendar/Calendar.jsx
- frontend/src/components/Modal.jsx
- Added event description field in frontend & backend query to save the same
- Modified modal to view description 
- Added handleKeyDown to close modal when Esc
- Fixes #379
https://github.com/user-attachments/assets/4b07c0ad-1246-4c62-a0ef-467b7de9a9ce
> Added event description field in frontend & backend query to save the same

- frontend/.env.example
- frontend/package.json
- frontend/src/components/Calendar/Calendar.jsx
- Added sync with google calendar to fetch events and show the same
- Fixes #382 
- You need to set CLIENT_ID and API_KEY with Calendar API enabled in .env of frontend
> Added sync with google calendar to fetch events and show the same

- frontend/src/components/Cards/NoteCard.jsx
- Added export button to download note in txt
- Fixes #383 
https://github.com/user-attachments/assets/6b1a14b0-e1ea-426f-9cbd-0b1c84122cc3
> Added export button to download note in txt

- frontend/src/pages/Home/AddEditNotes.jsx
- frontend/src/pages/Home/Home.jsx
- frontend/src/pages/Home/Templates.jsx
- Added pre-defined templates for Notes
- Added new button to select from templates
- Integrated Add/Edit notes with templates
- Fixes #384 
https://github.com/user-attachments/assets/5264fbe0-086d-4506-a635-db6104b03d88
---
> Added pre-defined templates for Notes

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components/Hero/Hero.jsx
- frontend/src/components/Progressbar.jsx
Fixes #385 
**Changes**:
1. Created the file "frontend/src/components/Progressbar.jsx" : Defined the on scroll progressbar here
2. In the file "frontend/src/components/Hero/Hero.jsx" : Removed the "ScrollOnTop" component which was showing only on the home page,
3. In the file "frontend/src/App.jsx" : Added the "Progressbar" component and the "ScrollToTop" component from the "react-simple-scroll-up" library
**Demo**:
https://www.loom.com/share/9c25015f18a24cfba216becdc4d5f84c?sid=9b2043c3-aad0-4d43-bcbe-c5c0fb49f872
> "Progress bar added & scroll to top button modified"

- backend/Makefile
- backend/controllers/noteControllers.js
- frontend/src/pages/Home/AddEditNotes.jsx
- frontend/src/pages/Home/Home.jsx
- Added mardown and code block support + Adjusted width of new note
- Fixes #389 
https://github.com/user-attachments/assets/f5ef7253-7fc8-4016-ac91-9a990b864d9a
> Added mardown and code block support + Adjusted width of new note

- frontend/src/pages/Home/Home.jsx
- Added Sort Notes by date in Ascending/Descending order
- Fixes #394 
https://github.com/user-attachments/assets/285e4064-cc5a-468f-b468-7e948ca7f56c
> Sort Notes by date in Ascending/Descending order

- frontend/src/pages/Home/AddEditNotes.jsx
- Fixes #393 
https://github.com/user-attachments/assets/5dbb370e-c330-4a5e-ad18-6cf09cad3f55
> Added revert button to get back last changes in edit Note

- frontend/src/App.jsx
- frontend/src/components/Contributors/Contributors.css
- frontend/src/components/Contributors/Contributors.jsx
- frontend/src/components/Footer.jsx
- Added contributors page and link in footer
- Fixes #395
https://github.com/user-attachments/assets/106196e2-440c-4471-8583-e5b322da2426
> Added contributors page and link in footer

- frontend/src/components/Navbar.jsx
- frontend/src/components/SearchBar/SearchBar.jsx
- frontend/src/pages/Home/Home.jsx
Added search by tag and search by title for Notes
- Fixes #392 
https://github.com/user-attachments/assets/2750a35d-e77a-4c5e-869f-0e5553eb5ca3
> Added search by tag and search by title for Notes

- backend/Routes/noteRoutes.js
- backend/controllers/noteControllers.js
- backend/package.json
- frontend/src/components/Cards/NoteCard.jsx
> Added share button to view note by link

- backend/Routes/user.routes.js
- backend/controllers/user.controllers.js
- backend/models/userModel.js
> Fix sign up

- frontend/src/components/Calendar/Calendar.jsx
> added loader to calender page
